# Generated by Django 4.0.3 on 2023-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_questionpaper_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
