# Generated by Django 4.0.3 on 2023-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_semester_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='file_url',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='file_url',
            new_name='file_id',
        ),
        migrations.AddField(
            model_name='note',
            name='file_format',
            field=models.CharField(default='PDF', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='file_format',
            field=models.CharField(default='PDF', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='month',
            field=models.CharField(default='JAN', max_length=20),
            preserve_default=False,
        ),
    ]
