# Generated by Django 4.0.3 on 2023-08-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_file_url_note_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
