# Generated by Django 4.0.3 on 2023-08-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questionpaper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='branch_id',
            field=models.ManyToManyField(related_name='semester', to='api.branch'),
        ),
    ]
