# Generated by Django 4.2.4 on 2023-08-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_note_thumb_questionpaper_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
